import { Promo } from './types';

export const promos: Promo[] = [
  { name: 'LEGO', discount: 10, description: 'our site give discount!' },
  { name: '2023', discount: 20, description: 'happy new year 2023!' },
];

export const cardsUrl = {
  americanExpress:
    'https://golfreviewsguide.com/wp-content/uploads/2021/10/The-American-Express-Logo.png?ezimgfmt=rs:311x187/rscb1/ngcb1/notWebP',
  visa: 'https://www.tadviser.ru/images/8/86/Visa_Inc._logo.svg.png',
  masterCard:
    'https://play-lh.googleusercontent.com/czro-ULAemRM1bMldf9gHQ7ajfa9NzKiZXFjI85mxawo60CaKMyHsjWaM38KHiZpsgY',
};

export const defaultSettings = {
  chosenCategories: {
    city: false,
    duplo: false,
    technic: false,
    frozen: false,
    creator: false,
  },
  chosenSizes: {
    small: false,
    large: false,
  },
  chosenNames: {
    FreightTrain: false,
    TrainStation: false,
    LunarResearchBase: false,
    LunarSpaceStation: false,
    MobileCrane: false,
    ExpressPassengerTrain: false,
    BarnFarmAnimals: false,
    FarmersMarketVan: false,
    LunarRovingVehicle: false,
    BathtubStuntBike: false,
    FireStation: false,
    TownCenter: false,
    AnnaAndOlafsCastleFun: false,
    ElsasCastleCourtyard: false,
    AnnaAndElsasFrozenWonderland: false,
    ElsaAndTheNokkStorybookAdventures: false,
    ElsasWagonAdventure: false,
    TheIceCastle: false,
    FrozenIceCastle: false,
    AnnasCastleCourtyard: false,
    Bookshop: false,
    HauntedHouse: false,
    SantasVisit: false,
    QueerEyeTheFab5Loft: false,
    Porsche911: false,
    NASAApollo11LunarLander: false,
    OptimusPrime: false,
    Colosseum: false,
    HighSpeedTrain: false,
    BackToTheFutureTimeMachine: false,
    RobotInventor: false,
    LEGOEducationBricQMotionPrimeSet: false,
    JeepWrangler: false,
    MaterialHandler: false,
    McLarenFormula1RaceCar: false,
    HeavydutyTowTruck: false,
    LamborghiniSianFKP37: false,
    FerrariDaytonaSP3: false,
    AppControlledCatD11Bulldozer: false,
    AppControlledTransformationVehicle: false,
    WildAnimalsOfEurope: false,
    NumberTrainLearnToCount: false,
    spaceShuttleMission: false,
    CarParkAndCarWash: false,
    FireEngine: false,
    SantasGingerbreadHouse: false,
    CodingExpress: false,
    AnimalTrain: false,
    WildAnimalsOfTheOcean: false,
    TruckTrackedExcavator: false,
  },
  priceRange: [7.99, 1458.99],
  amountRange: [1, 8],
}
