export enum LegoCategory {
  City = 'city',
  Duplo = 'duplo',
  Technic = 'technic',
  Frozen = 'frozen',
  Creator = 'creator',
}

export enum LegoSize {
  Small = 'small',
  Large = 'large',
}

export enum Interest {
  Animals = 'animals',
  Buildings = 'buildings',
  Cars = 'cars',
  Robots = 'robots',
  Fantasy = 'fantasy',
  Princesses = 'princesses',
  RealLifeHeroes = 'real-life heroes',
  Space = 'space',
  Trains = 'trains',
  Travel = 'travel',
  Vehicles = 'vehicles',
}

export enum LegoName {
  FreightTrain = 'Freight Train',
  TrainStation = 'Train Station',
  LunarResearchBase = 'Lunar Research Base',
  LunarSpaceStation = 'Lunar Space Station',
  MobileCrane = 'Mobile Crane',
  ExpressPassengerTrain = 'Express Passenger Train',
  BarnFarmAnimals = 'Barn & Farm Animals',
  FarmersMarketVan = 'Farmers Market Van',
  LunarRovingVehicle = 'Lunar Roving Vehicle',
  BathtubStuntBike = 'Bathtub Stunt Bike',
  FireStation = 'Fire Station',
  TownCenter = 'Town Center',
  AnnaAndOlafsCastleFun = "Anna and Olaf's Castle Fun",
  ElsasCastleCourtyard = 'Elsa’s Castle Courtyard',
  AnnaAndElsasFrozenWonderland = "Anna and Elsa's Frozen Wonderland",
  ElsaAndTheNokkStorybookAdventures = 'Elsa and the Nokk Storybook Adventures',
  ElsasWagonAdventure = "Elsa's Wagon Adventure",
  TheIceCastle = 'The Ice Castle',
  FrozenIceCastle = 'Frozen Ice Castle',
  AnnasCastleCourtyard = 'Anna’s Castle Courtyard',
  Bookshop = 'Bookshop',
  HauntedHouse = 'Haunted House',
  SantasVisit = 'Santa’s Visit',
  QueerEyeTheFab5Loft = 'Queer Eye – The Fab 5 Loft',
  Porsche911 = 'Porsche 911',
  NASAApollo11LunarLander = 'NASA Apollo 11 Lunar Lander',
  OptimusPrime = 'Optimus Prime',
  Colosseum = 'Colosseum',
  HighSpeedTrain = 'High-Speed Train',
  BackToTheFutureTimeMachine = 'Back to the Future Time Machine',
  RobotInventor = 'Robot Inventor',
  LEGOEducationBricQMotionPrimeSet = 'LEGO® Education BricQ Motion Prime Set',
  JeepWrangler = 'Jeep® Wrangler',
  MaterialHandler = 'Material Handler',
  McLarenFormula1RaceCar = 'McLaren Formula 1™ Race Car',
  HeavydutyTowTruck = 'Heavy-duty Tow Truck',
  LamborghiniSianFKP37 = 'Lamborghini Sián FKP 37',
  FerrariDaytonaSP3 = 'Ferrari Daytona SP3',
  AppControlledCatD11Bulldozer = 'App-Controlled Cat® D11 Bulldozer',
  AppControlledTransformationVehicle = 'App-Controlled Transformation Vehicle',
  WildAnimalsOfEurope = 'Wild Animals of Europe',
  NumberTrainLearnToCount = 'Number Train - Learn To Count',
  spaceShuttleMission = 'space Shuttle Mission',
  CarParkAndCarWash = 'Car Park and Car Wash',
  FireEngine = 'Fire Engine',
  SantasGingerbreadHouse = 'Santas Gingerbread House',
  CodingExpress = 'Coding Express',
  AnimalTrain = 'Animal Train',
  WildAnimalsOfTheOcean = 'Wild Animals of the Ocean',
  TruckTrackedExcavator = 'Truck & Tracked Excavator',
}
